### ISSUE TITLE
High Memory Use

### ISSUE THREAD

**Issue by vorte** [guillaumekln/faster-whisper#249] opened 2023-05-19 08:11 UTC
I've been testing faster-whisper for a little while and quite like the results. Thank you for your hard work. 👍 

However, I've been having problems with memory use on larger files. As an example, I have a very long audio file (5.5 hours) which I am transcribing in a container with 4 cpu cores and 16gb RAM available. I cannot share the file as it is copyrighted, but it is just speech with very little silence. Example code:

```
model = WhisperModel("small.en", device="cpu", cpu_threads=8, compute_type="int8")
segments, info = model.transcribe(audio_file.name, word_timestamps=True)
```

This tends to run for about 2hrs with the container memory utilization gradually growing from ~10% all the way to 100% at which point the container hits an OOM and is killed. It almost feels like there's some sort of memory leak.

I started with a lower memory allocation and kept increasing to 16gb, but every time I try a longer file I hit an OOM. I also tried running the same file with float32 compute type and got the same result. Am I missing something? Anything I can try to get around this?

**Comment by guillaumekln** [comment] 2023-05-19 18:39
I don't reproduce this issue. I let a transcription run for 1h using the same options as you and the memory usage is pretty constant. I don't think it will change if I let the script run longer.

Is anything else happening in your code? What are you doing with the generated segments?

**Comment by vorte** [comment] 2023-05-20 16:13
Just writing the output to a text file. The whole file ends up being less than 2MB, so I doubt that the problem is there, but maybe I'm not seeing something?

More complete example (OOM on the nested for loop):

```
# download audio file from S3

model = WhisperModel("small.en", device="cpu", cpu_threads=8, compute_type="int8")
segments, info = model.transcribe(audio_file.name, word_timestamps=True)

 with tempfile.NamedTemporaryFile(suffix='.txt', mode='w', delete=False) as output_file:
        for segment in segments:
            for word in segment.words:
                output_file.write("%.3f,%.3f,%s\n" % (word.start, word.end, word.word))

# upload transcript file to S3
```

I am using version 0.5.1 btw.

**Comment by guillaumekln** [comment] 2023-05-20 16:27
Can you set the environment variable `CT2_VERBOSE=1` before running the script and report the logging output here?

```
CT2_VERBOSE=1 python3 …
```

**Comment by vorte** [comment] 2023-05-20 17:27
I'm running this now. The env var added a bunch of extra output on startup, but the transcription is currently running and not producing any output (same as before). The memory use is growing, though, so I'll leave it on to see if extra output is added before the OOM. I'll update the comment when it completes.

```
[2023-05-20 16:51:07.763] [ctranslate2] [thread 1] [info] CPU: GenuineIntel (SSE4.1=true, AVX=true, AVX2=true, AVX512=true)
[2023-05-20 16:51:07.763] [ctranslate2] [thread 1] [info]  - Selected ISA: AVX2
[2023-05-20 16:51:07.763] [ctranslate2] [thread 1] [info]  - Use Intel MKL: true
[2023-05-20 16:51:07.763] [ctranslate2] [thread 1] [info]  - SGEMM backend: MKL (packed: false)
[2023-05-20 16:51:07.763] [ctranslate2] [thread 1] [info]  - GEMM_S16 backend: MKL (packed: false)
[2023-05-20 16:51:07.763] [ctranslate2] [thread 1] [info]  - GEMM_S8 backend: MKL (packed: false, u8s8 preferred: true)
[2023-05-20 16:51:08.739] [ctranslate2] [thread 1] [info] Loaded model /root/.cache/huggingface/hub/models--guillaumekln--faster-whisper-small.en/snapshots/4e49ce629e3fa4c3da596c602b212cb026910443 on device cpu:0
[2023-05-20 16:51:08.739] [ctranslate2] [thread 1] [info]  - Binary version: 6
[2023-05-20 16:51:08.739] [ctranslate2] [thread 1] [info]  - Model specification revision: 3
[2023-05-20 16:51:08.739] [ctranslate2] [thread 1] [info]  - Selected compute type: int8
```

**Comment by vorte** [comment] 2023-05-22 12:23
This was an issue with my specific setup. 

I had 4 cpu cores (multithreaded) available to the container and 8 threads set on the model parameter. Setting the cpu threads down to 4 seemed to resolve the issue - memory remains at under 2GB use for the whole 2hrs of transcription.

The memory growing in the way that it did still seems unusual, though.

**Comment by mrfragger** [comment] 2023-05-25 17:39
good to know...I transcribe 36 hour audiobooks daily to vtt and I set my thread count to 8 which is max my computer can handle.

**Comment by guillaumekln** [comment] 2023-06-21 13:01
I did not manage to reproduce this issue. I'm closing it since you manage to solve the problem. In general you should not set more threads than the number of CPU cores anyway.

If anyone can provide a way to consistently reproduce the issue (e.g. using a Docker container with CPU restrictions), please update this thread again.

**Closed by guillaumekln** 2023-06-21 13:01 UTC
