### ISSUE TITLE
Different output for `medium` between openai/whisper and this

### ISSUE THREAD

**Issue by emhagman** [guillaumekln/faster-whisper#10] opened 2023-02-18 18:27 UTC
Hi,

First, let me start by saying great job. This is awesome! It's crazy how much faster this is than `openai/whisper`. I really appreciate the effort here.

I am running into a few issues and just want to better understand.

I am on the latest `ctranslate2==3.6.0` and am using the `medium` model both with a `beam_size=5` set. On `faster-whisper`, I get:

```
 ______ available?î Yeah. Speaker? ______, this is
```

And on `openai/whisper` I get:

_I am using `[NAME]` here._
```
 __________ Hello. __________ Hello, is [NAME] available? __________ Yes, speaking. __________ Hi,
```

I have other examples of this as well but need to redact the text before I can post them.

I've also noticed non-English characters in the translation as well for `faster-whisper` for English-only audio. And even on `3.6.0`, I still appear to get the beginning of my audio chopped off as well (but not all the time). It's seemingly random.

Is it normal to have some differences? Is there come config difference I am missing between the two?

While the speed increases are great, the inconsistencies are enough that we can't really use this over `openai/whisper` for our tasks. Anything I can do to help debug, let me know.

As a side note, I've been testing `medium.en` and the random characters seem to not happen and accuracy appears to be better for `faster-whisper` compared to the multi language model for `faster-whisper` where as `medium` for `openai/whsiper` appears to work fine.

Thanks in advanced!

**Comment by guillaumekln** [comment] 2023-02-18 20:02
Hi,

Differences are expected for segments that trigger the "temperature fallback", which is based on random sampling. This is likely what you are observing here since you noticed non-English characters in the output.

Can you try without the temperature fallback? For faster-whisper you can set `temperature=0`, for openai/whisper you can run with `--temperature_increment_on_fallback None`.

If you are observing difference after that, it would be great if you can provide a way to reproduce it.

But in general it's almost impossible to guarantee the same output. Even openai/whisper will not be consistent with itself when run on another device or system.

**Comment by emhagman** [comment] 2023-02-18 20:57
> Hi,
> 
> Differences are expected for segments that trigger the "temperature fallback", which is based on random sampling. This is likely what you are observing here since you noticed non-English characters in the output.
> 
> Can you try without the temperature fallback? For faster-whisper you can set `temperature=0`, for openai/whisper you can run with `--temperature_increment_on_fallback None`.
> 
> If you are observing differences after that, it would be great if you can provide a way to reproduce it.
> 
> But in general it's almost impossible to guarantee the same output. Even openai/whisper will not be consistent with itself when run on another device or system.

Perfect, thank you. I'll try on Monday and get back to you. For now, it seems the `medium.en` model is doing much better for `faster-whisper`

**Comment by guillaumekln** [comment] 2023-02-19 08:38
You can also consider trying the `large` model in faster-whisper. It will still be faster and use less memory than the `medium` in openai/whisper.

**Comment by emhagman** [comment] 2023-02-19 17:54
When using `temperature=0`, I just get a bunch of silence:

```
Estimating duration from bitrate, this may be inaccurate
Detected language 'en' with probability 0.995432
[0.00s -> 30.00s]  __________________________________________________________
[30.00s -> 32.00s]  __________________________________________________________________
[60.00s -> 62.00s]  __________________________________________________________________
[90.00s -> 92.00s]  ______________________________________________________________
```

I will try `large` next and see what happens w/o changing the temperature.

**Comment by guillaumekln** [comment] 2023-02-20 15:36
Thanks for the feedback.

I reproduced a similar issue with the medium model and found this to be related to FP16 execution.

Can you help testing [a change](https://github.com/OpenNMT/CTranslate2/pull/1090) that makes some operations run in higher precision? Go to the [build page](https://github.com/OpenNMT/CTranslate2/actions/runs/4223962782), download the artifact "python-wheels", extract the archive, and install the appropriate wheel.

Hopefully this change will fix the transcription failures you are observing. There may be other small differences with the openai/whisper output, but I believe this is fine as long as the overall quality is preserved.

**Comment by emhagman** [comment] 2023-02-20 16:00
> Thanks for the feedback.
> 
> I reproduced a similar issue with the medium model and found this to be related to FP16 execution.
> 
> Can you help testing [a change](https://github.com/OpenNMT/CTranslate2/pull/1090) that makes some operations run in higher precision? Go to the [build page](https://github.com/OpenNMT/CTranslate2/actions/runs/4223962782), download the artifact "python-wheels", extract the archive, and install the appropriate wheel.
> 
> Hopefully this change will fix the transcription failures you are observing. There may be other small differences with the openai/whisper output, but I believe this is fine as long as the overall quality is preserved.

Sure I can test this out today, thank you!

**Comment by emhagman** [comment] 2023-02-20 17:30
@guillaumekln With this w/ `large`, I am getting some weird output still.

`libcode.exe is not available in this session` for example shows up in the beginning of my text.
As well as `。 vpng` for another audio file.

**Comment by guillaumekln** [comment] 2023-02-20 17:53
You should still set this compute type argument to "float16". The compute type mentioned in the PR is related to an external library.

"auto" is resolved to "int8_float16" on GPU which is no longer comparable to openai/whisper.

Can you retry with the "float16" compute type?

**Comment by emhagman** [comment] 2023-02-20 17:54
> float16

Will do!

**Comment by emhagman** [comment] 2023-02-20 17:57
> "auto" is resolved to "int8_float16" on GPU which is no longer comparable to openai/whisper.

Would this also explain beginnings of the audio being cut still as well?

**Comment by emhagman** [comment] 2023-02-20 18:11
Okay, so with `large` and `float16`, still get weird results:

```
                                                         Okay, so now do you have a complete bar kit? Not yet, no. 
```

I am trying one last thing to be super sure. I am using `pip install --no-deps` to make sure the old `ctranslate2` is not being installed somehow and explicitly setting all the dependencies.

**Comment by guillaumekln** [comment] 2023-02-20 19:53
Thanks for all the tests.

So what happens if you set `compute_type="float"`? Do you get the expected outputs?

**Comment by emhagman** [comment] 2023-02-20 19:54
> Thanks for all the tests.
> 
> So what happens if you set `compute_type="float"`? Do you get the expected outputs?

Of course :) I actually did do that (I saw your other PR) and I am still seeing all those issues.

The loop from above, for example, is using `float`:
```
They will be asked questions on how to do certain tasks and will be asked questions on how to do certain tasks and will be asked questions on how to do certain tasks and will be asked questions on how to do questions on how to do certain tasks and will be asked questions on how to do certain tasks and will be asked questions on how to do сл
```

**Comment by guillaumekln** [comment] 2023-02-20 20:01
For completeness, could you post the command line that you used to convert the model and the code snippet you use to get the transcription from faster-whisper?

**Comment by emhagman** [comment] 2023-02-20 20:04
> For completeness, could you post the command line that you used to convert the model and the code snippet you use to get the transcription from faster-whisper?

`!ct2-transformers-converter --model openai/whisper-large --output_dir whisper-large-ct2 --quantization float16`

Should I switch this to `float` as well now that I am using `float`?

```
segments, info = self.transcription_model.transcribe(filename, initial_prompt=self.prompt)
logger.info("detected language '%s' with probability %f" % (info.language, info.language_probability))
full_text = ""
for segment in segments:
    logger.info("transcribed [%.2fs -> %.2fs]" % (segment.start, segment.end))
    full_text += segment.text  # remove double whitespace, etc
logger.info(f"finished transcription for: {filename}")
```

**Comment by emhagman** [comment] 2023-02-20 20:59
Something I've noticed is, at least for that loop, that includes some of my `initial_prompt` text I am passing down. With `openai/whisper` it doesn't loop with the same prompt.

**Comment by emhagman** [comment] 2023-02-20 23:23
Sorry to keep bugging you with updates but I switched to `openai/whisper` for a few hours to just to sanity check and sometimes it skips beginning of audio, etc as well. Is this something where really I should have a process to re-run transcription when it looks like it failed?

I'm thinking maybe I just need a different approach where I detect bad/missing text and then re-run. Thoughts?

**Comment by guillaumekln** [comment] 2023-02-21 08:50
The "temperature fallback" that was proposed by the authors is already a mechanism that re-runs the transcription when it is considered failed. So I'm not sure it is useful to add another fallback layer.

Also, I just realized that the "large" model in openai/whisper is actually the new large-v2 version: https://github.com/openai/whisper/blob/9f7aba609971434b9de2a8d34ca2de766976904d/whisper/__init__.py#L28-L29

The large-v2 version is a separate model in the Hugging Face Hub, so you should convert `openai/whisper-large-v2` when comparing the large size.

**Comment by emhagman** [comment] 2023-02-21 17:06
> The "temperature fallback" that was proposed by the authors is already a mechanism that re-runs the transcription when it is considered failed. So I'm not sure it is useful to add another fallback layer.
> 
> Also, I just realized that the "large" model in openai/whisper is actually the new large-v2 version: https://github.com/openai/whisper/blob/9f7aba609971434b9de2a8d34ca2de766976904d/whisper/__init__.py#L28-L29
> 
> The large-v2 version is a separate model in the Hugging Face Hub, so you should convert `openai/whisper-large-v2` when comparing the large size.

Will do! Thanks. I assume this still won't fix some of the other issues we've been seeing?

**Comment by emhagman** [comment] 2023-02-21 18:12
I have very limited results so far but with `large-v2` and the latest master `wheel` from `ctranslate2`, things seem a lot better. Thank you so much. I'll keep you posted if I notice anything strange.

**Comment by guillaumekln** [comment] 2023-02-22 09:42
Thanks for the info.

As I get more feedback, I'm finding more small differences with the reference implementation. I'm not sure how impactful they are, but it's good to address them:

* When computing the average log prob, they add a "+ 1" to the sequence length that we did not do. Fixed in https://github.com/guillaumekln/faster-whisper/commit/e47e00910a0c985be0f63bb7d6ba5f11fbaa9d39
* The leading space should be removed before computing the compression ratio. Fixed in https://github.com/guillaumekln/faster-whisper/commit/4b8237da1bb9ef6ad7c2ef858af9e6d05c8cd93b
* I read the reference code incorrectly and wrongly assume the EOS score was not included in the greedy search score. Fixed in https://github.com/OpenNMT/CTranslate2/pull/1096

**Comment by emhagman** [comment] 2023-02-22 21:23
> Thanks for the info.
> 
> As I get more feedback, I'm finding more small differences with the reference implementation. I'm not sure how impactful they are, but it's good to address them:
> 
> * When computing the average log prob, they add a "+ 1" to the sequence length that we did not do. Fixed in [e47e009](https://github.com/guillaumekln/faster-whisper/commit/e47e00910a0c985be0f63bb7d6ba5f11fbaa9d39)
> * The leading space should be removed before computing the compression ratio. Fixed in [4b8237d](https://github.com/guillaumekln/faster-whisper/commit/4b8237da1bb9ef6ad7c2ef858af9e6d05c8cd93b)
> * I read the reference code incorrectly and wrongly assumed the EOS score was not included in the greedy search score. Fixed in [Also include the EOS score in Whisper greedy search OpenNMT/CTranslate2#1096](https://github.com/OpenNMT/CTranslate2/pull/1096)

This is great, thank you so much for all your work. Any way you can cut a new release soon for `3.6.1`?

**Comment by guillaumekln** [comment] 2023-02-23 10:19
I just published the version 3.7.0 with the latest changes.

**Comment by emhagman** [comment] 2023-02-23 16:47
> I just published `ctranslate2==3.7.0` with the latest changes.

Thank you!

**Comment by guillaumekln** [comment] 2023-03-03 11:01
Hi @emhagman, do you think we can close this issue? Or are there still important differences with openai/whisper?

**Closed** 2023-03-03 17:31 UTC

**Comment by zara0m** [comment] 2023-03-29 21:35
Hello,

I have a problem for Italian language. I was testing some samples from fleur dataset with small - int8 quantized model, beam_size=1, on windows. For some audios, it fell into a loop and it doesn't generate output. I tried with temperature 0 and it didn't change. 
I attached a sample here.
I appreciate it if you could help me fix this.




https://user-images.githubusercontent.com/26019580/228672893-24edf894-9bb4-4a98-b5cd-d1de11252a71.mp4

**Comment by guillaumekln** [comment] 2023-03-30 10:22
Hi,

Thank you for sharing the audio! This example helped me find another small difference with openai/whisper. This requires an update of the model configuration to disable the generation of the task tokens `<|transcribe|>` and `<|translate|>`.

The new configuration is automatically downloaded if you load the model from a model size like:

```python
WhisperModel("small", compute_type="int8")
```

If you converted the model yourself, you can either download the [updated `config.json`](https://huggingface.co/guillaumekln/faster-whisper-small/blob/main/config.json) or manually set the `suppress_tokens` argument:

```python
model.transcribe(..., suppress_tokens=[-1, 50358, 50359])
```

Note that the temperature fallback seems helpful for this example, so you should remove `temperature=0` before testing again.

**Comment by zara0m** [comment] 2023-03-30 13:38
Great! Thank you very much!

**Comment by zara0m** [comment] 2023-04-17 15:38
Oh sorry, they are:
small quantized model, compute_type="int8_float16" , beam_size=1, on windows, using cuda. BTW, when I use int8 for compute type, it works fine, the problem is only for "int8_float16".

Thanks.
