### ISSUE TITLE
Audio stream using web-sockets not able to be transcribed by faster-whisper.

### ISSUE THREAD

**Issue by JayAdityaNautiyal** [guillaumekln/faster-whisper#386] opened 2023-07-28 14:25 UTC
So we were looking to use real-time audio from the client side and stream it as data buffers to the backend. But fasterWhisper transcribes the initial audio stream only and when the second stream comes as a data buffer, it throws an error :

**Invalid data found when processing input: '«none>'**

This is the client side inspection logs, where we can see that it works for the first audio stream i.e "Let's Go" and fails for the second audio stream. However, it works again for the first stream if client connection is refreshed.
<img width="605" alt="image" src="https://github.com/guillaumekln/faster-whisper/assets/80779224/14c33c3b-0e29-49de-a6ee-bc3fc9febda3">

And this is the error log in the server side:

<img width="1020" alt="image" src="https://github.com/guillaumekln/faster-whisper/assets/80779224/b1bc48dc-837a-4e39-b0f0-da74d7098594">

And this is how we use faster-whisper in code:
<img width="498" alt="image" src="https://github.com/guillaumekln/faster-whisper/assets/80779224/521ea685-6589-42bf-a6d2-d903ff216152">

Kindly help guys!
This makes us stuck and we can't move no forward!

_Originally posted by @JayAdityaNautiyal in https://github.com/guillaumekln/faster-whisper/issues/361#issuecomment-1655773196_

**Comment by guillaumekln** [comment] 2023-07-28 14:28
Duplicate of #386.

**Closed by guillaumekln** 2023-07-28 14:28 UTC
