### ISSUE TITLE
Different output from mono audio and stereo audio

### ISSUE THREAD

**Issue by zanjabil2502** [guillaumekln/faster-whisper#11] opened 2023-02-20 09:36 UTC
Previously, I would like to say very grateful for this project. I have a fairly unique problem, namely the transcript results obtained from mono audio and stereo audio are quite different. The transcript results from stereo audio are better than mono audio, even though we know that before the transcript process, the audio will be converted to mono.

Parameters used:
compute_type : int8
model : large
device: gpu
beam_size: 5
language: 'id'

Link Audio:
[In Here](https://drive.google.com/drive/folders/1hZ6pqer1u6NXfbLe0D7sPR_wLGvlosS3?usp=sharing)

**Comment by guillaumekln** [comment] 2023-02-20 14:53
How did you convert the stereo file to mono?

I tried this [ffmpeg command](https://stackoverflow.com/a/51494497) to convert your stereo file to mono, and I got the same transcription with both files.

**Comment by zanjabil2502** [comment] 2023-02-20 15:41
I use the your program which is in faster-whisper in decode_audio.

I will try your suggest. Actually, I have tested several types of mono and stereo audio, but what I get is if the audio is not clear and there is noise, the stereo results will be better.

**Comment by guillaumekln** [comment] 2023-02-24 14:10
Let me close this as it does not seem there is an issue with the code.

Note that openai/whisper will output the same differences between your mono and stereo files. So the issue is more related to how you acquired the mono audio or how you converted the stereo audio to mono.

**Closed by guillaumekln** 2023-02-24 14:10 UTC
